-- ============================================================================
-- BOOKING OVERLAP GUARD
-- ----------------------------------------------------------------------------
-- WHY
--   booking-guard.sql added a unique index on (provider_id, date, start_time)
--   for active sessions, which stops two bookings that START at the same time.
--   It does NOT stop bookings that merely OVERLAP:
--
--       09:00–12:00  booked   (Hair)
--       10:00–11:00  booked   (Nails)   <-- different start_time, sails through
--
--   The stylist is then double-booked for 10:00–11:00. Reported in testing:
--   "I booked a slot in between an existing slot and it allowed me to."
--
--   Root cause is two-fold: the availability editor allowed OVERLAPPING SLOTS to
--   be created (now blocked client-side), and the DB had no overlap check. This
--   is the half that actually guarantees it — it holds even for overlapping slots
--   that already exist, and against a hand-crafted API call.
--
--   Raises errcode 23505 deliberately: the app already handles that code on the
--   booking insert with a friendly "That time was just booked" + back to the time
--   step (apply-session.tsx:500), so no client change is needed.
--
--   Active = pending|accepted, matching booking-guard.sql and taken_slots — a
--   completed/declined/cancelled booking frees the time again.
-- ============================================================================

-- ===========================================================================
-- ⚠⚠ THE DDL THAT WAS HERE IS NOW OWNED BY MIGRATION 0096. DO NOT RE-ADD IT.
--
-- This file created `reject_overlapping_session()` and
-- `trg_reject_overlapping_session`. Both were adopted VERBATIM by 0096 (item
-- 199) and the copies were deleted on 9 Oct 2026, so there is no second
-- definition left to drift.
--
-- ✅ WHY DELETED RATHER THAN BROUGHT FORWARD. The copy that was here had already
-- gone stale in three ways without anything noticing:
--
--   1. `set search_path = public` — 0094 appended `pg_temp` (item 202), so the
--      live object was `public, pg_temp` and this file would have reverted it.
--   2. The live body was reformatted — the early return on one line, the `where`
--      clause collapsed — so re-running this would have rewritten it.
--   3. Every explanatory comment below was ALREADY absent from the live body.
--
-- ⚠️ ITS SIBLING, `session-status-guard.sql`, HAD DRIFTED FURTHER AND MORE
-- DANGEROUSLY: it held a pre-0070 status guard with no `not_held` branch while
-- promising "This file is safe to re-run". Re-running it would have made
-- `report_not_held` raise "Illegal status transition" on every use. **Keeping a
-- second copy of a live object is the hazard; bringing it forward only resets
-- the clock.** Item 199.
--
-- To change either object now, write a migration. To read the live one:
--   select pg_get_functiondef('public.reject_overlapping_session()'::regprocedure);
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- ✅ THE RULE THE DELETED BODY NO LONGER EXPLAINS, KEPT BECAUSE THIS IS THE
-- ONLY PLACE IT WAS EVER WRITTEN DOWN — and now also in 0096's
-- `comment on function`, so it lives on the object itself.
--
--   * Active = pending|accepted. completed/declined/cancelled/expired free the
--     time again, matching booking-guard.sql and taken_slots.
--   * ⚠️ HALF-OPEN: `s.start_time < new.end_time and s.end_time > new.start_time`.
--     So 09:00-10:00 and 10:00-11:00 do NOT clash, while 09:00-12:00 and
--     10:00-11:00 do. Back-to-back bookings must keep working.
--   * errcode 23505 deliberately, because the app already handles that code on
--     the booking insert with "That time was just booked".
--   * `s.id <> new.id` so an UPDATE does not clash with itself.
--
-- ⚠️ AND WHAT IT CANNOT DO, which the original WHY above does not say: it is a
-- BEFORE trigger running a SELECT, so it CANNOT see an uncommitted row in a
-- concurrent transaction. It is not a substitute for `sessions_active_slot_uniq`
-- (0093), and 0090's claim that the index is "the only thing preventing a double
-- booking" is corrected in 0093's header.
-- ---------------------------------------------------------------------------

-- ============================================================================
-- PRE-CHECK — existing overlapping active bookings. The trigger only guards NEW
-- writes, so anything already overlapping stays until resolved. Should be empty:
--   select a.id, b.id, a.date, a.start_time, a.end_time, b.start_time, b.end_time
--   from public.sessions a
--   join public.sessions b
--     on a.provider_id = b.provider_id and a.date = b.date and a.id < b.id
--    and a.start_time < b.end_time and b.start_time < a.end_time
--   where a.status in ('pending','accepted') and b.status in ('pending','accepted');
--
-- VERIFY
--   In-app: book 09:00-12:00, then try to book 10:00-11:00 with the same stylist
--   on the same date -> rejected with "That time was just booked".
--   Back-to-back must still work: 09:00-10:00 then 10:00-11:00 -> both succeed.
--   A cancelled/declined booking frees its time -> re-booking works.
-- ============================================================================
