-- ============================================================================
-- ⚠️ SUPERSEDED — THIS FILE NO LONGER CONTAINS ANY SQL. DO NOT RESTORE IT.
--
-- It is kept for what it explains, not for what it did. Audit item 123,
-- 25 Sep 2026.
--
-- ── WHAT IT USED TO DO, AND WHY THAT WAS A PROBLEM ─────────────────────────
-- Applied by hand on 21 Jul 2026, it redefined nearby_models so the RPC
-- returned model attributes and the stylist dashboard's 26 filter chips
-- stopped returning zero results every time.
--
-- ⚠️ TWO HAND-RUN FILES THEN DEFINED ONE FUNCTION. `nearby-models-any.sql`
-- came later and replaced this body wholesale, to make "Any" mean everyone —
-- this version required `u.latitude is not null and u.longitude is not null`,
-- so a model who never granted location was invisible at every radius. And
-- migration 0018 later added the blocked-pair exclusion on top.
--
-- So by 25 Sep this file's body was behind on both counts. Running it would
-- have made every model without coordinates disappear again AND removed
-- `not public.is_blocked_pair(...)`, surfacing people a member had blocked —
-- a safety control, undone by a file somebody ran to fix filter chips.
--
-- Two files with one function's name is the trap itself, even while they
-- happen to agree, so only one of them keeps a body:
--
--   → supabase/nearby-models-any.sql is the live definition, brought forward
--     from pg_get_functiondef on 25 Sep 2026. Edit that one.
--
-- Nothing here is executable any more, which is the point: a file that cannot
-- run cannot be run by mistake. scripts/check-handrun-drift.mjs no longer sees
-- this file at all, because it creates nothing.
--
-- ── WHAT IS WORTH KEEPING FROM IT ──────────────────────────────────────────
-- Two decisions, both still true of the live function:
--
--   * LEFT JOIN on model_attributes is deliberate. An inner join would drop
--     every model who has not filled in their attributes — most of them at
--     launch — shrinking the nearby list instead of enriching it.
--
--   * CREATE OR REPLACE cannot change a function's return type, so any change
--     to the returned columns has to drop first. Dropping also drops
--     privileges, which is why the live file re-grants at the end.
--
-- ── IF YOU NEED THE OLD BODY ───────────────────────────────────────────────
-- It is in git history, at the commit before this file was emptied. It is not
-- here because a superseded definition sitting next to a current one is how
-- the wrong one gets pasted at two in the morning.
-- ============================================================================
