-- ============================================================================
-- SESSION STATUS GUARD — stop self-accept / self-complete
-- ----------------------------------------------------------------------------
-- WHY
--   The `sessions` UPDATE RLS policy allows any PARTICIPANT to update the row, with
--   no check on the status column. A model could therefore PATCH status directly via
--   the API — self-accepting their own application, or self-completing a booking to
--   unlock a (fake) review. RLS WITH CHECK can't express this: it sees only the NEW
--   row, not the OLD → NEW transition. A BEFORE UPDATE trigger can.
--
-- INTENDED TRANSITIONS (from the app's real flows):
--   pending  -> accepted   PROVIDER only   (sessions.tsx, provider-dashboard.tsx)
--                          — and only while the appointment is still ahead (0066)
--   pending  -> expired    THE SCHEDULED JOB only, null-uid path (0067)
--   pending  -> declined   PROVIDER only
--   accepted -> completed  PROVIDER only   (sessions.tsx, chat/[sessionId].tsx)
--   pending/accepted -> cancelled  EITHER PARTY  (block-driven, chat/[sessionId].tsx)
--   completed / declined / cancelled / expired = TERMINAL (no further change)
--
--   The model never legitimately sets accepted/declined/completed. Service-role edge
--   functions (auth.uid() null) and admins bypass, since RLS already blocks anon and
--   only trusted server code runs without a user JWT.
-- ============================================================================

-- ===========================================================================
-- ⚠⚠⚠ THE DDL THAT WAS HERE WAS DANGEROUS AND IS NOW OWNED BY MIGRATIONS.
-- DO NOT RE-ADD IT. DO NOT RECONSTRUCT IT FROM AN OLD COMMIT.
--
--   `enforce_session_status_transition()`  →  owned by migration **0070**
--   `trg_enforce_session_status`           →  adopted by migration **0096**
--
-- ⚠⚠ WHY "DANGEROUS" AND NOT JUST "STALE". The copy that was here was the
-- pre-0070 version: **no `not_held` branch and no CV004.** Its own header said
-- *"This file is safe to re-run."* It was not.
--
-- `report_not_held` (0070) does `update public.sessions set … status =
-- 'not_held'`. The trigger is BEFORE UPDATE OF status, it fires for every role,
-- and it returns early only for admins and a null `auth.uid()`. So re-running
-- the deleted copy would have made `new.status = 'not_held'` fall through to the
-- `else` branch and raise **"Illegal status transition accepted -> not_held"** —
-- **breaking the "it did not happen" feature, which is moderation evidence, on
-- every single use.**
--
-- ✅ The live guard was measured as 0070's on 9 Oct 2026 (not_held branch and
-- CV004 present, 3182 chars, md5 be5d87a2…). **The database was correct; this
-- file was the stale one.** 0096 records that measurement as a precondition, so
-- the version this copy would have reverted is pinned in a migration rather than
-- only in a deleted file.
--
-- ⚠️ IT WAS MARKED AND THE MARKER DID NOT SAVE IT. The line here read
-- `-- MIGRATION-OWNS: enforce_session_status_transition 0066` while 0070 had
-- redefined the function, and `check-handrun-drift` only verified that the NAME
-- was marked — so it reported a DECLARED overlap, which reads as checked. The
-- checker now verifies the NUMBER against the latest migration defining the
-- name. That is what finally pointed at this.
--
-- To change the guard now, write a migration. To read the live one:
--   select pg_get_functiondef('public.enforce_session_status_transition()'::regprocedure);
-- ===========================================================================


-- ============================================================================
-- VERIFY
--   In-app (must still work): provider accepts a pending application; provider marks
--   an accepted session complete; a block cancels the pair's pending/accepted sessions.
--   Exploit (must now fail with 42501): a model PATCHing their own session to
--   'accepted' or 'completed' via the API.
--   Quick SQL simulation of the exploit (run as the model, expect an exception):
--     -- set the JWT to the model, then:
--     -- update sessions set status='completed' where id='<their pending session>';
-- ============================================================================
