// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // .expo is generated by the Expo CLI on every start. It carries its own
    // eslint-disable comments, which drift and then get reported as stale
    // directives — a warning about a file nobody edits, in a gate that has to
    // sit at zero warnings to be worth anything.
    ignores: ["dist/*", ".expo/*"],
  }
]);
