import { useEffect, useState } from 'react';
import { useColorScheme as useRNColorScheme } from 'react-native';

/**
 * To support static rendering, this value needs to be re-calculated on the client side for web
 */
export function useColorScheme() {
  const [hasHydrated, setHasHydrated] = useState(false);

  /**
   * ⚠️ DOCUMENTED EXCEPTION - react-hooks/set-state-in-effect, 8 Sep 2026.
   *
   * This file is generated by the Expo template and is the documented way to
   * detect hydration on web. The rule is correct in the abstract and there is
   * no better expression of "I am now on the client" available here.
   *
   * It also only ever runs on web. This app ships Android; the .web variant is
   * reached by `expo start --web` alone. Rewriting Expo's own idiom, in a file
   * no shipped client loads, to satisfy a lint rule is not worth the divergence
   * from upstream.
   */
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setHasHydrated(true);
  }, []);

  const colorScheme = useRNColorScheme();

  if (hasHydrated) {
    return colorScheme;
  }

  return 'light';
}
